"""Add missing columns to company_info table

Revision ID: e5e3fe1f1ec4
Revises: c385de52d363
Create Date: 2025-10-07 15:10:54.368352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e3fe1f1ec4'
down_revision = 'c385de52d363'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_analytics_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('facebook_pixel_code', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('custom_css', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('custom_js', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('skills', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('facebook_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('instagram_url', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('order_position', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('order_position')
        batch_op.drop_column('featured')
        batch_op.drop_column('is_active')
        batch_op.drop_column('instagram_url')
        batch_op.drop_column('facebook_url')
        batch_op.drop_column('skills')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')
        batch_op.drop_column('position')

    with op.batch_alter_table('company_info', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('custom_js')
        batch_op.drop_column('custom_css')
        batch_op.drop_column('facebook_pixel_code')
        batch_op.drop_column('google_analytics_code')

    # ### end Alembic commands ###
